sudo: false
language: erlang
otp_release:
   - 18.1
   - 18.0
   - 17.5
   - 17.4
   - 17.3
   - 17.1
   - R16B
   - R15B03
   - R15B02
   - R15B01
script:
  - make eunit
branches:
  only:
    - master
